package com.cn.model;

import java.util.Date;

public class CustomerDevice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_device.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_device.customer_id
     *
     * @mbggenerated
     */
    private Customer customer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_device.device_id
     *
     * @mbggenerated
     */
    private Device device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_device.status
     *
     * @mbggenerated
     */
    private String status;

    private Integer useCount;
    private Integer chargeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_device.create_date
     *
     * @mbggenerated
     */
    private Date createTime;

    public CustomerDevice() {
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public Device getDevice() {
        return device;
    }

    public void setDevice(Device device) {
        this.device = device;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Integer getUseCount() {
        return useCount;
    }

    public void setUseCount(Integer useCount) {
        this.useCount = useCount;
    }

    public Integer getChargeCount() {
        return chargeCount;
    }

    public void setChargeCount(Integer chargeCount) {
        this.chargeCount = chargeCount;
    }
}