package com.cn.model;

import java.math.BigDecimal;

public class Device {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device.Id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device.charge_ count
     *
     * @mbggenerated
     */

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device.lat
     *
     * @mbggenerated
     */
    private BigDecimal lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device.lon
     *
     * @mbggenerated
     */
    private BigDecimal lon;

    public Device(String id, String name, BigDecimal lat, BigDecimal lon) {
        this.id = id;
        this.name = name;

        this.lat = lat;
        this.lon = lon;

    }

    public Device() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device.Id
     *
     * @return the value of t_device.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device.name
     *
     * @return the value of t_device.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device.charge_ count
     *
     * @return the value of t_device.charge_ count
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device.use_count
     *
     * @return the value of t_device.use_count
     *
     * @mbggenerated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device.lat
     *
     * @return the value of t_device.lat
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BigDecimal getLat() {
        return lat;
    }

    public void setLat(BigDecimal lat) {
        this.lat = lat;
    }

    public BigDecimal getLon() {
        return lon;
    }

    public void setLon(BigDecimal lon) {
        this.lon = lon;
    }
}