package com.cn.model;

import java.util.Date;

public class Record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record.Id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record.customer_device_id
     *
     * @mbggenerated
     */
    private String customerDeviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record.user_time
     *
     * @mbggenerated
     */
    private Date useTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_record
     *
     * @mbggenerated
     */
    public Record(String id, String customerDeviceId, Date useTime) {
        this.id = id;
        this.customerDeviceId = customerDeviceId;
        this.useTime = useTime;
    }

    public Record() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record.Id
     *
     * @return the value of t_record.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record.customer_device_id
     *
     * @return the value of t_record.customer_device_id
     *
     * @mbggenerated
     */
    public String getCustomerDeviceId() {
        return customerDeviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record.user_time
     *
     * @return the value of t_record.user_time
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    public void setCustomerDeviceId(String customerDeviceId) {
        this.customerDeviceId = customerDeviceId;
    }

    public Date getUseTime() {
        return useTime;
    }

    public void setUseTime(Date useTime) {
        this.useTime = useTime;
    }
}